// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddList(arg1) {
  return window['go']['main']['App']['AddList'](arg1);
}

export function Addboard(arg1) {
  return window['go']['main']['App']['Addboard'](arg1);
}

export function GetBoardIdentities() {
  return window['go']['main']['App']['GetBoardIdentities']();
}

export function GetBoards() {
  return window['go']['main']['App']['GetBoards']();
}

export function GetOsUserName() {
  return window['go']['main']['App']['GetOsUserName']();
}

export function GetTestJSON() {
  return window['go']['main']['App']['GetTestJSON']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadBoardsDir() {
  return window['go']['main']['App']['ReadBoardsDir']();
}

export function RemoveBoard(arg1) {
  return window['go']['main']['App']['RemoveBoard'](arg1);
}

export function SetCurrentBoard(arg1) {
  return window['go']['main']['App']['SetCurrentBoard'](arg1);
}
