// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Addboard(arg1) {
  return window['go']['main']['App']['Addboard'](arg1);
}

export function GetBoards() {
  return window['go']['main']['App']['GetBoards']();
}

export function GetOsUserName() {
  return window['go']['main']['App']['GetOsUserName']();
}

export function GetTestJSON() {
  return window['go']['main']['App']['GetTestJSON']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveBoard(arg1) {
  return window['go']['main']['App']['RemoveBoard'](arg1);
}
