// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBoard(arg1:string,arg2:string,arg3:string):Promise<Array<main.WorkspaceCacheIdentity>>;

export function AddList(arg1:main.List):Promise<main.Board>;

export function ChangeCurrentBoard(arg1:string,arg2:string):Promise<main.Board>;

export function DeleteList(arg1:string):Promise<main.Board>;

export function GetCurrentBoard():Promise<main.Board>;

export function GetOsUserName():Promise<string>;

export function GetTestJSON():Promise<string>;

export function GetWorkspaceIdentities():Promise<Array<main.WorkspaceCacheIdentity>>;

export function Greet(arg1:string):Promise<string>;

export function ReadBoardsDir():Promise<Array<string>>;

export function UpdateLists(arg1:Array<main.List>):Promise<main.Board>;
