// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Addboard(arg1:main.Board):Promise<Array<main.Board>>;

export function GetBoards():Promise<Array<main.Board>>;

export function GetOsUserName():Promise<string>;

export function GetTestJSON():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RemoveBoard(arg1:string):Promise<Array<main.Board>>;
